import React from "react";
import Link from "next/link";

const Home = () => {
    return (
        <div
            style={{
                height: "100vh",
                padding: "20px",
                backgroundColor: "#232323",
                color: "white",
            }}
        >
            <h1 style={{ fontSize: "48px", marginBottom: "20px" }}>Homepage</h1>
            <p style={{ fontSize: "18px", marginBottom: "30px" }}>
                This project was generated by{" "}
                <a
                    href="/"
                    style={{ color: "#87CEFA", textDecoration: "none" }}
                >
                    sourabh bhakar
                </a>
                . Quickly use the links below to navigate through all pages.
            </p>
            <ul style={{ listStyle: "none", padding: "0" }}>
                <li style={{ marginBottom: "10px" }}>
                    <Link href="/newhomepageweb" style={{ color: "#87CEFA", textDecoration: "none" }}>
                        Newhomepageweb
                    </Link>
                </li>
                <li style={{ marginBottom: "10px" }}>
                    <Link href="/login" style={{ color: "#87CEFA", textDecoration: "none" }}>
                        Login
                    </Link>
                </li>
            </ul>
        </div>
    );
};

export default Home;
